CREATE TABLE pharmacy.pharmacy_drug
(
    id            INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name          VARCHAR(100),
    stock         INTEGER,
    price         DOUBLE PRECISION,
    reorder_level INTEGER,
    pharmacy_id   INTEGER,
    CONSTRAINT pk_pharmacy_drug PRIMARY KEY (id)
);

ALTER TABLE pharmacy.pharmacy_drug
    ADD CONSTRAINT FK_PHARMACY_DRUG_ON_PHARMACY FOREIGN KEY (pharmacy_id) REFERENCES pharmacy.pharmacy (id);