CREATE TABLE pharmacy.pharmacy
(
    id      INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name    VARCHAR(100),
    address VARCHAR(200),
    phone   VARCHAR(20),
    CONSTRAINT pk_pharmacy PRIMARY KEY (id)
);