CREATE TABLE pharmacy.record
(
    id       INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    date     date,
    quantity INTEGER,
    drug_id  INTEGER,
    CONSTRAINT pk_record PRIMARY KEY (id)
);

ALTER TABLE pharmacy.record
    ADD CONSTRAINT FK_RECORD_ON_DRUG FOREIGN KEY (drug_id) REFERENCES pharmacy.drug (id);