SET search_path = "pharmacy";
DROP SCHEMA IF EXISTS "pharmacy" CASCADE;

CREATE SCHEMA "pharmacy";

CREATE TABLE pharmacy.pharmacy
(
    id      INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name    VARCHAR(100),
    address VARCHAR(200),
    phone   VARCHAR(20),
    CONSTRAINT pk_pharmacy PRIMARY KEY (id)
);

CREATE TABLE pharmacy.pharmacy_drug
(
    name          VARCHAR(100) NOT NULL,
    description   VARCHAR(200),
    stock         INTEGER,
    price         DOUBLE PRECISION,
    reorder_level INTEGER,
    pharmacy_id   INTEGER,
    CONSTRAINT pk_pharmacy_drug PRIMARY KEY (name)
);

ALTER TABLE pharmacy.pharmacy_drug
    ADD CONSTRAINT FK_PHARMACY_DRUG_ON_PHARMACY FOREIGN KEY (pharmacy_id) REFERENCES pharmacy.pharmacy (id);

CREATE TABLE pharmacy.record
(
    id       INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    date     date,
    quantity INTEGER,
    drug_id  VARCHAR(100),
    CONSTRAINT pk_record PRIMARY KEY (id)
);

ALTER TABLE pharmacy.record
    ADD CONSTRAINT FK_RECORD_ON_DRUG FOREIGN KEY (drug_id) REFERENCES pharmacy.pharmacy_drug (name);

CREATE TABLE pharmacy.pharmacist
(
    cpr         BIGINT NOT NULL,
    name        VARCHAR(100),
    surname     VARCHAR(100),
    password    VARCHAR(50),
    phone       VARCHAR(20),
    birthday    date,
    gender      TEXT,
    pharmacy_id INTEGER,
    CONSTRAINT pk_pharmacist PRIMARY KEY (cpr)
);

ALTER TABLE pharmacy.pharmacist
    ADD CONSTRAINT FK_PHARMACIST_ON_PHARMACY FOREIGN KEY (pharmacy_id) REFERENCES pharmacy.pharmacy (id);